<?php

/**
 * @file
 * Contains mbta_routes_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Url;
use \Drupal\node\Entity\Node;

/**
 * Add template suggestions for different types of block.
 * @param  array  $suggestions
 * @param  array  $variables
 */
function mbta_routes_list_theme_suggestions_block_alter(array &$suggestions, array $variables)
{
    if ($variables['elements']['#plugin_id'] == 'my_account_widget') {

        // Attach different template depending on field value.
        switch ($variables['elements']['#configuration']['type']) {
            case 'dropdown':
                $suggestions[] = 'block__my_account_widget_dropdown';
                break;
            case 'list':
                $suggestions[] = 'block__my_account_widget_list';
                break;
        }
    }
};

function mbta_routes_list_preprocess_input__password(&$vars) {

  $vars['attributes']['class'][] = 'form-control';
  $vars['attributes']['data-toggle'] = 'password';
}

function mbta_routes_list_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $phone_number = $form['field_user_phone_number'];
  $phone_number['#weight'] = 0.001;
  $account = [
    '#type' => 'container',
    '#weight' => -10,
    'mail' => $form['account']['mail'],
    'name' => $form['account']['name'],
    'field_user_phone_number' => $phone_number,
    'pass' => $form['account']['pass'],
    'status' => $form['account']['status'],
    'roles' => $form['account']['roles'],
    'notify' => $form['account']['notify'],
  ];
  $account['name']['#access'] = false;
  $account['name']['#required'] = false;
  $form['account'] = $account;
  $form['actions']['submit']['#value'] = t('Complete Sign-up');
  $form['actions']['submit']['#submit'][] = 'my_account_user_register_custom_submit_handler';
  unset($form['field_user_phone_number']);
}

function mbta_routes_list_form_user_edit_subscription_details_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = 'my_account_edit_subscription_details_form_submit_handler';
  unset($form['account']['name']);
  unset($form['account']['pass']);
  unset($form['account']['status']);
  unset($form['account']['roles']);
  unset($form['account']['notify']);
  //ksm($form);
}

function mbta_routes_list_entity_create(\Drupal\Core\Entity\EntityInterface $entity) {
  if($entity->getEntityTypeId() == 'user' && $entity->id() != NULL) {

  }
}

function mbta_routes_list_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if($entity->getEntityTypeId() == 'user' && $entity->id() != NULL) {
    if(!$entity->field_shopping_list->getValue()) {
      $shopping_list = Node::create([
        'type' => 'shopping_list',
        'title' => 'Weekly Grocery List',
        'uid' => $entity->id(),
      ]);
      if ($shopping_list->save()) {
        $entity->field_shopping_list->setValue([['target_id' => $shopping_list->id()]]);
      }
    }
  }
}

function mbta_routes_list_user_register_custom_submit_handler($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // set relative internal path
  $redirect_path = "/welcome";
  $url = url::fromUserInput($redirect_path);
  // set redirect
  $form_state->setRedirectUrl($url);
  $ri_controller = new ReachInfluenceController;
  $user_data = $form_state->getValues();
  $user_ri_data = [
    'retailer_identifier' => "rinatural",
  	'first_name' => $user_data['field_first_name'][0]['value'],
  	'last_name' => $user_data['field_last_name'][0]['value'],
  	'email' => $user_data['mail'],
  	'password' => $user_data['pass'],
  	'phone_number' => $user_data['field_user_phone_number'][0]['value'],
  ];
  $current_user = \Drupal::currentUser();
  $user = \Drupal\user\Entity\User::load($current_user->id());

  $ri_controller->registerUser($user_ri_data, $user);
}

function mbta_routes_list_edit_subscription_details_form_submit_handler($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $ri_controller = new ReachInfluenceController;
  $user_data = $form_state->getValues();
  $user_ri_data = [
    'retailer_identifier' => "rinatural",
  	'first_name' => $user_data['field_first_name'][0]['value'],
  	'last_name' => $user_data['field_last_name'][0]['value'],
  	'email' => $user_data['mail'],
  	'password' => $user_data['current_pass'],
  	'phone_number' => $user_data['field_user_phone_number'][0]['value'],
  	'address' => $user_data['field_profile_address'][0]['address']['address_line1'],
  	'address1' => $user_data['field_profile_address'][0]['address']['address_line2'],
  	'city' => $user_data['field_profile_address'][0]['address']['locality'],
  	'state' => $user_data['field_profile_address'][0]['address']['administrative_area'],
  	'postal_code' => $user_data['field_profile_address'][0]['address']['postal_code'],
  	'birth_date' => $user_data['field_birth_date'][0]['value']->format('m/d/Y'),
  ];
  //ksm($user_ri_data);
  $current_user = \Drupal::currentUser();
  $user = \Drupal\user\Entity\User::load($current_user->id());
  $ri_controller->registerUser($user_ri_data, $user);
}

function mbta_routes_list_preprocess_form__user_register_form(&$vars) {
  $handler = \Drupal::service('theme_handler');
  $path = $handler->getTheme('naturalgrocers')->getPath();
  $vars['npower_image_src'] = '/'.$path.'/images/npower_logo_alt.png';
}
